### ISSUE TITLE
Support for auto-scrolling when coach mark items are off the screen

### ISSUE THREAD

**Issue by meham09** [svenjacobs/reveal#48]
Integrating content with coachmarks items that are off the screen produces a crash since the current version does not support the functionality to scroll to the desired item if it's off the screen.

Will a future version provide the support that'd scroll the coach mark item if it's off the screen?

**Comment by svenjacobs** [comment]
Hello @meham09,

could you please provide a sample project which reproduces this issue?

**Comment by blackbirdsr71br** [comment]
Hi, can you resolve this, thanks

**Comment by svenjacobs** [comment]
I still need a sample project 🥲 OP has not delivered yet.

**Comment by svenjacobs** [comment]
Reveal cannot know when a revealable item is in a lazy container and it also cannot magically scroll to it. It is the duty of the developer to ensure that a revealable item is visible on the screen before calling `reveal()`. The reason why Reveal crashes here is because the item at that time is not known to Reveal because it is not part of the composition when it's outside the visible area.

So please ensure that the item is visible before calling `reveal()`. Additionally you can check `revealableKeys` of `RevealState` to ensure that Reveal knows the item before calling the function.

What I can do is add a `tryReveal` function which does not crash. However this doesn't change the fact that the reveal effect is not shown for items outside the visible area.
