### ISSUE TITLE
Revealable layout issue

### ISSUE THREAD

**Issue by jayesh408** [svenjacobs/reveal#56]
**Describe the bug**
When I have compose screen inside a fragment which under activity which is having toolbar, reveal box is rendered without considering the padding for the toolbar. Basically it reveals the content above it. (refer screenshot)

**To Reproduce**
1. Have an activity with toolbar and below that fragment container both in LinearLayout
2. Have some content in fragment under toolbar
3. Try to reveal some component
4. You'll see that It didn't consider toolbar padding and revealed box is rendered above the compoennt not on the component

**Screenshots**
<img width="283" alt="Screenshot 2023-07-24 at 3 49 03 PM" src="https://github.com/svenjacobs/reveal/assets/121788890/178464a2-5a4d-494e-8939-0fb13a97e0e8">

**Sample project**
[Reveal-issue.zip](https://github.com/svenjacobs/reveal/files/12144702/Reveal-issue.zip)

**Additional context**
I see this modifier extension 
```
override fun Modifier.revealable(
		keys: Iterable<Key>,
		shape: RevealShape,
		padding: PaddingValues,
	)
```

is putting the Revealable using 

```
layout = Revealable.Layout(
     offset = layoutCoordinates.positionInRoot(),
     size = layoutCoordinates.size.toSize(),
)
```

Here I believe we should use layoutCoordinates.positionInWindow() instead, because in case of anyone having mix of compose and fragments and there's a toolbar in activity it'll consider root as content within the fragment which is wrong and rendering wrong. 

**Note:** 
changing to positionInWindow() doesn't solve the problem completely, after changing to window we also have to subtract the status bar padding to make it completely work, something like below

<img width="1089" alt="Screenshot 2023-07-24 at 3 15 16 PM" src="https://github.com/svenjacobs/reveal/assets/121788890/e87b0510-1aae-4a77-83a5-c0f1bf9f4780">

Lemme know what you think about the issue, or is it something else. We're blocked due to this issue, rendering is not happening correct

**Comment by svenjacobs** [comment]
Thanks for the bug report.

Does it actually make a difference whether you use `positionInWindow() - Offset(...)` or `positionInRoot() - Offset(...)`?

**Comment by jayesh408** [comment]
Yes it'll make the difference. Whole point is to calculate the position relative to window and not the root. No?

**Comment by svenjacobs** [comment]
Could it be similar to [this](https://github.com/svenjacobs/reveal/issues/49#issuecomment-1621787248) issue?

**Comment by jayesh408** [comment]
No, I've already verified. Its not because of the fitSystemWindows thing. 
If you see the setup, Revealable works fine for the activity which is compose only. Or would even work for the onces where activity's fragment is fullscreen. 

But in particular cases where content is below toolbar or something. That time it'll not work as expected

**Comment by svenjacobs** [comment]
What is the Android SDK version you tested this with?

I believe this could have something to do with how `ComposeView` [consumes window insets](https://issuetracker.google.com/issues/241812630#comment2). Prior to SDK 30 if views consumed insets, insets were not available for other views in the subsequent hierarchy. The overlay however is based on [Fullscreen](https://github.com/svenjacobs/reveal/blob/802814cf4fe653692b439bc659da4d0b334caeb3/reveal-core/src/main/kotlin/com/svenjacobs/reveal/internal/fullscreen/Fullscreen.kt) which adds another `ComposeView` instance to the root content view.

So do you see a difference between API 30+ and API 29 and below?

**Comment by jayesh408** [comment]
Lemme verify once

**Comment by jayesh408** [comment]
**No, I don't see any difference. Its running on API 29**

<img width="270" alt="Screenshot 2023-07-25 at 10 06 00 AM" src="https://github.com/svenjacobs/reveal/assets/121788890/f5a4d5b8-5ba4-485e-8efb-511a64c08e9e">

**Comment by svenjacobs** [comment]
You're right, it has nothing to do with this bug / behaviour of Android.
I did a bit more investigation and found out the following:

When using `positionInRoot()` you get the position relative to the root composable. In your sample project that's below the toolbar because that is where the `FrameLayout` is where you place the `Fragment`, which again renders the `ComposeView`. That's the reason why the reveal effect is misplaced by the height of the toolbar. Reveal uses [Fullscreen](https://github.com/svenjacobs/reveal/blob/802814cf4fe653692b439bc659da4d0b334caeb3/reveal-core/src/main/kotlin/com/svenjacobs/reveal/internal/fullscreen/Fullscreen.kt) which inserts a new `ComposeView` into Android's root container. So the overlay is placed on the same view layer as the `activity_other_main.xml` layout. That's also the reason why the overlay covers the whole screen, even above the toolbar, which I assume is generally the desired behaviour.

When using `positionInWindow()` you get the absolute position on the screen (let's forget about the term "window" for now because I believe that the underlying function `View.getLocationOnScreen()` from API 1 has nothing to do with modern multi-window support). So it's the position from the top left corner (`0,0`) of the screen **including** any system components like the status bar. Now the reveal effect is misplaced by the height of the status bar because the overlay starts right below it.

First of all Reveal should use `positionInWindow()` but that doesn't solve the problem completely as described above.
With `positionInWindow()` there are the following solutions to this problem:

* In your `Activity` call `WindowCompat.setDecorFitsSystemWindows(window, false)`. This makes sure that your layout is rendered behind the status bar. However then you need to apply the top padding to your toolbar manually. [Insetter](https://github.com/chrisbanes/insetter) helps with this.
* I could add an `Offset` parameter to the `revealable()` modifier. The developer has to pass the height of the status bar manually.

**Comment by svenjacobs** [comment]
> First of all Reveal should use `positionInWindow()`

However this will break Reveal for any users that rely on the current behaviour and don't use `WindowCompat.setDecorFitsSystemWindows(window, false)`. Maybe we should keep using `positionInRoot()` but still introduce the offset. The offset would in your case then be the height of the toolbar. I guess this makes more sense?

**Comment by jayesh408** [comment]
Yeh makes sense. In this case 
- I'll call `WindowCompat.setDecorFitsSystemWindows(window, false)` on activity
- Have statusBarPadding() on the root composable 
- Offset the Reveal by providing toolbar height to the revelable parameter


This will solve my issue I believe

**Comment by jayesh408** [comment]
**Thanks a lot** 🙌  @svenjacobs
